theme: jekyll-theme-leap-day

title: Fold-A-Bike by Green Mile
description: The team - Green Mile - solution to the GlobalXChanges Challenge 2021, hold by the University of Applied Sciences Munich in corporation with Deutsche Bahn Connect GmbH
